server:
  port: 8082

spring:
  application:
    name: BankAppListenerService
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/activemq
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.bankappservice: DEBUG
  file:
    name: C:/Workspace/logs/bankapplistenerservice.log